services:
  - type: web
    name: sign_lang-to-voice_system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false          # set this in Render dashboard
    healthCheckPath: /health
